---
title: "R Notebook"
author: "Maitry Shah"
output:
  pdf_document: default
  html_notebook: default
---
```{r message=FALSE}


library(Lahman)
library(dplyr)
library(skimr)

```
```{r}
library(pacman)

p_load(tidyverse, tictoc, feather, naniar, DataExplorer, textreadr,plyr,nycflights13)
```
```{r message=FALSE}
weather20181 <- read_csv(file="./data/2018_1.csv")
weather20182<- read_csv(file="./data/2018_2.csv")
weather20184 <- read_csv(file="./data/2018_4.csv")
weather20185 <- read_csv(file="./data/2018_5.csv")
weather20188 <- read_csv(file="./data/2018_8.csv")
weather20189 <- read_csv(file="./data/2018_9.csv")
weather201811 <- read_csv(file="./data/2018_11.csv")
weather201812 <- read_csv(file="./data/2018_12.csv")
```


```{r}


weather2018 <- rbind.fill(weather20181, weather20182, weather20184, weather20185,
                            weather20188, weather20189, weather201811,weather201812)

##glimpse(weather2018)

```
```{r}
weather2018=weather2018[c(1:57)]
##glimpse(weather2018)
```

```{r}

flights1 <- flights %>% mutate(Origin = toupper(origin))
head(flights1)

```
```{r}
weather_new=slice(weather2018,1:10000)
flights1=slice(flights1,1:10000)
```

```{r}

sfoflights18=inner_join(weather_new,flights1,by = "Origin")
```
\newpage

Origin freq

OAK	   34667			
SFO	   115208			
SJC	   36025	

```{r}
weather2018 %>% filter(Origin=='SFO' | Origin=='SJC' | Origin=='OAK') %>% 
  select(Origin) %>%
  group_by(Origin) %>% count()
```
\newpage
## Based on 3963748 observation with 76 Variable

cancelled   mean_dep_delay   mean_arr_delay

38156	      8.861102	       4.677967	

```{r}
 sfoflights18%>%
  
  summarise(cancelled = sum(is.na(arr_delay)), 
            
            mean_dep_delay = mean(dep_delay,na.rm=TRUE),
            mean_arr_delay = mean(arr_delay,na.rm=TRUE)) 
```
\newpage
```{r}
sfoflights18 %>% select(year, month, day, tailnum) %>%
  filter(tailnum == "N725MQ") %>%
  group_by(year,month) %>%
  count() 
```
```{r}
sfoflights18 %>% filter(tailnum == "N725MQ") %>%
  group_by(DayOfWeek) %>%
  tally() %>%
  ggplot(aes(x = DayOfWeek, y = n)) +
  geom_point() +
  geom_line()
```
\newpage
```{r}
sfoflights18 %>% 
  filter(tailnum == "N725MQ") %>%
  group_by(DayOfWeek) %>%
  tally() %>% 
  ggplot(aes(x=DayOfWeek, y=n)) +
  geom_point() +
  geom_line() +
  geom_smooth()
```

\newpage

```{r}
weather %>%
      filter(month == 7) %>%
      ggplot(aes(x = temp)) +
      geom_histogram() +
      labs(x = "Temperature", y = "Counts", title = "Distribution of temperature in July, 2013")

```
\newpage
relationship between dewp and humid
```{r}
weather%>%
      ggplot(aes(x = dewp, y = humid)) +
      geom_point(size = 1) +
      geom_smooth() +
      labs(title = "Relationship between humid and dewp")
```
\newpage
relationship between precip and visib
```{r}
weather%>%
      ggplot(aes(x = precip, y = visib)) +
      geom_point(size = 1) +
      geom_smooth() +
      labs(title = "Relationship between precip and visib")
```

